const crypto = require('crypto');
const moment = require('moment-timezone');
const accessEventRepository = require('../../repositories/accessEventRepository');
const activityRepository = require('../../repositories/activityRepository');
const { getAdapterForIntercom } = require('./hikvision/adapterFactory');

const DEVICE_TIMEZONE = process.env.DEVICE_TIMEZONE || 'America/Santiago';
const configuredLookbackDays = Number.parseInt(process.env.ACCESS_EVENT_INITIAL_LOOKBACK_DAYS || '30', 10);
const INITIAL_LOOKBACK_MS = Math.min(Math.max(configuredLookbackDays || 30, 1), 365) * 24 * 60 * 60 * 1000;
const OVERLAP_MS = 5 * 60 * 1000;
const PAGE_SIZE = 30;
const MAX_PAGES = 100;

// Hikvision MAJOR_EVENT (5) minor codes. `currentVerifyMode` describes the
// configured authentication plan; the minor code identifies what happened.
const ACCESS_EVENT_DESCRIPTORS = new Map([
    [1, { method: 'card', methodLabel: 'Tarjeta', description: 'Acceso mediante tarjeta', status: 'succeeded' }],
    [2, { method: 'card_pin', methodLabel: 'Tarjeta + PIN', description: 'Acceso mediante tarjeta y PIN', status: 'succeeded' }],
    [3, { method: 'card_pin', methodLabel: 'Tarjeta + PIN', description: 'Tarjeta o PIN rechazado', status: 'failed' }],
    [16, { method: 'combined', methodLabel: 'Autenticación combinada', description: 'Acceso mediante autenticación combinada', status: 'succeeded' }],
    [38, { method: 'fingerprint', methodLabel: 'Huella', description: 'Acceso mediante huella', status: 'succeeded' }],
    [39, { method: 'fingerprint', methodLabel: 'Huella', description: 'Huella rechazada', status: 'failed' }],
    [54, { method: 'face_fingerprint', methodLabel: 'Rostro + huella', description: 'Acceso mediante rostro y huella', status: 'succeeded' }],
    [55, { method: 'face_fingerprint', methodLabel: 'Rostro + huella', description: 'Rostro o huella rechazado', status: 'failed' }],
    [57, { method: 'face_pin', methodLabel: 'Rostro + PIN', description: 'Acceso mediante rostro y PIN', status: 'succeeded' }],
    [58, { method: 'face_pin', methodLabel: 'Rostro + PIN', description: 'Rostro o PIN rechazado', status: 'failed' }],
    [60, { method: 'face_card', methodLabel: 'Rostro + tarjeta', description: 'Acceso mediante rostro y tarjeta', status: 'succeeded' }],
    [61, { method: 'face_card', methodLabel: 'Rostro + tarjeta', description: 'Rostro o tarjeta rechazado', status: 'failed' }],
    [75, { method: 'face', methodLabel: 'Rostro', description: 'Acceso mediante rostro', status: 'succeeded' }],
    [76, { method: 'face', methodLabel: 'Rostro', description: 'Rostro rechazado', status: 'failed' }],
    [77, { method: 'employee_face', methodLabel: 'ID + rostro', description: 'Acceso mediante ID y rostro', status: 'succeeded' }],
    [78, { method: 'employee_face', methodLabel: 'ID + rostro', description: 'ID o rostro rechazado', status: 'failed' }],
    [101, { method: 'pin', methodLabel: 'PIN', description: 'Acceso mediante PIN', status: 'succeeded' }],
    [102, { method: 'pin', methodLabel: 'PIN', description: 'PIN rechazado', status: 'failed' }],
    [153, { method: 'combined', methodLabel: 'Autenticación combinada', description: 'Acceso mediante autenticación combinada', status: 'succeeded' }],
]);

// These are physical state/relay notifications generated by a single access.
// They are useful as low-level telemetry but must not become extra access rows.
const TECHNICAL_DOOR_EVENT_MINORS = new Set([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 29, 30, 31, 32]);

function formatDeviceTime(value) {
    return moment(value).tz(DEVICE_TIMEZONE).format('YYYY-MM-DDTHH:mm:ssZ');
}

function parseDeviceTime(value) {
    if (!value) return new Date();
    const text = String(value);
    const parsed = /(Z|[+-]\d\d:\d\d)$/.test(text)
        ? moment.parseZone(text)
        : moment.tz(text, DEVICE_TIMEZONE);
    return parsed.isValid() ? parsed.toDate() : new Date();
}

function employeeNoFromEvent(event) {
    return event.employeeNoString || event.employeeNo || event.EmployeeNo || null;
}

function eventDescription(event) {
    return event.eventDescription || event.description || event.label || event.eventType || null;
}

function accessEventDescriptor(event) {
    return ACCESS_EVENT_DESCRIPTORS.get(Number(event.minor)) || null;
}

function shouldPersistAccessEvent(event) {
    return !TECHNICAL_DOOR_EVENT_MINORS.has(Number(event.minor));
}

function eventStatus(event) {
    const descriptor = accessEventDescriptor(event);
    if (descriptor) return descriptor.status;
    const description = String(eventDescription(event) || '').toLowerCase();
    const inductiveType = Number(event.inductiveEventType || event.inductiveEvent || 0);
    if (inductiveType === 1) return 'succeeded';
    if (inductiveType === 2) return 'failed';
    if (/fail|invalid|denied|illegal|expired|error|rechaz|fallid|inválid|inval/.test(description)) return 'failed';
    return 'recorded';
}

function correlationId(device, event, occurredAt) {
    const serial = event.serialNo ?? event.SerialNo;
    if (serial !== undefined && serial !== null) {
        return `${device.device_id}:${serial}:${occurredAt.toISOString()}`;
    }
    const stable = JSON.stringify({
        deviceId: device.device_id,
        time: occurredAt.toISOString(),
        employeeNo: employeeNoFromEvent(event),
        major: event.major,
        minor: event.minor,
        doorNo: event.doorNo,
        readerNo: event.cardReaderNo,
        description: eventDescription(event),
    });
    return `${device.device_id}:${crypto.createHash('sha256').update(stable).digest('hex')}`;
}

function eventMetadata(event, subject) {
    const descriptor = accessEventDescriptor(event);
    return {
        employeeNo: employeeNoFromEvent(event),
        subjectName: subject?.subject_name || event.name || null,
        subjectType: subject?.subject_type || 'unknown',
        description: descriptor?.description || eventDescription(event),
        method: descriptor?.method || null,
        methodLabel: descriptor?.methodLabel || null,
        major: event.major ?? null,
        minor: event.minor ?? null,
        inductiveEventType: event.inductiveEventType ?? null,
        doorNo: event.doorNo ?? null,
        cardReaderNo: event.cardReaderNo ?? null,
        configuredVerifyMode: event.currentVerifyMode || event.verifyMode || null,
        attendanceStatus: event.attendanceStatus || null,
        serialNo: event.serialNo ?? null,
    };
}

async function persistDeviceEvent(device, event) {
    if (!shouldPersistAccessEvent(event)) return false;
    const employeeNo = employeeNoFromEvent(event);
    const occurredAt = parseDeviceTime(event.time || event.dateTime);
    const subject = await accessEventRepository.resolveEventSubject(device.device_id, employeeNo, occurredAt);
    const participants = subject?.owner_user_id
        ? [{ userId: subject.owner_user_id, role: 'invitation_owner' }]
        : [];
    await activityRepository.createActivity({
        condominiumId: device.condominium_id,
        deviceId: device.device_id,
        actorUserId: subject?.actor_user_id || null,
        eventType: 'access',
        status: eventStatus(event),
        source: 'hikvision_access',
        correlationId: correlationId(device, event, occurredAt),
        occurredAt,
        metadata: eventMetadata(event, subject),
        participants,
    });
    return true;
}

async function syncDeviceAccessEvents(device) {
    const adapter = await getAdapterForIntercom(device);
    if (!adapter.supportsStoredAccessEvents) return { deviceId: device.device_id, skipped: true };

    const latest = await accessEventRepository.findLatestEventTime(device.device_id);
    const now = new Date();
    const start = latest
        ? new Date(new Date(latest).getTime() - OVERLAP_MS)
        : new Date(now.getTime() - INITIAL_LOOKBACK_MS);
    const searchID = crypto.randomUUID().replace(/-/g, '');
    let position = 0;
    let imported = 0;

    for (let page = 0; page < MAX_PAGES; page += 1) {
        const result = await adapter.searchAccessEvents({
            position,
            maxResults: PAGE_SIZE,
            major: 5,
            minor: 0,
            startTime: formatDeviceTime(start),
            endTime: formatDeviceTime(new Date(now.getTime() + 60_000)),
            picEnable: false,
            timeReverseOrder: false,
            searchID,
        });
        if (!result.ok) {
            throw new Error(`Access event query failed with HTTP ${result.status}: ${JSON.stringify(result.data)}`);
        }
        const events = Array.isArray(result.data.InfoList) ? result.data.InfoList : [];
        for (const event of events) {
            if (await persistDeviceEvent(device, event)) imported += 1;
        }
        const matched = Number(result.data.numOfMatches ?? events.length);
        position += matched;
        if (result.data.responseStatusStrg !== 'MORE' || matched === 0) break;
    }

    return { deviceId: device.device_id, imported };
}

async function syncAllAccessEvents() {
    const devices = await accessEventRepository.findSyncableIntercoms();
    const results = [];
    for (const device of devices) {
        try {
            results.push(await syncDeviceAccessEvents(device));
        } catch (error) {
            console.error(`[ACCESS EVENT SYNC ${device.device_id}]`, error.message);
            results.push({ deviceId: device.device_id, error: error.message });
        }
    }
    return results;
}

module.exports = {
    accessEventDescriptor,
    employeeNoFromEvent,
    eventStatus,
    shouldPersistAccessEvent,
    syncDeviceAccessEvents,
    syncAllAccessEvents,
};
